import type { Conversation, AppSettings, ChannelCredentials } from './types';

const now = new Date();
const mins = (m: number) => new Date(now.getTime() - m * 60 * 1000);
const hours = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);

export const DEMO_CONVERSATIONS: Conversation[] = [
  // ── Messenger ──────────────────────────────────────────────────────────────
  {
    id: 'conv-1',
    channelType: 'messenger',
    channelId: 'ch-messenger-1',
    contactName: 'Karen Booth',
    contactInitials: 'KB',
    contactAvatarColor: '#9C27B0',
    pageName: "Dave's Electrical Services",
    unreadCount: 3,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-1-3',
      conversationId: 'conv-1',
      direction: 'incoming',
      text: "It's a 4-bed detached, built in 1970. The fuse box is the old ceramic type.",
      timestamp: mins(3),
      channelType: 'messenger',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-1-1',
        conversationId: 'conv-1',
        direction: 'incoming',
        text: 'Hi Dave, I need a full rewire quote. Can you help?',
        timestamp: mins(20),
        channelType: 'messenger',
        isRead: true,
      },
      {
        id: 'msg-1-2',
        conversationId: 'conv-1',
        direction: 'outgoing',
        text: 'Thank you for your enquiry, I appreciate it. Please could you take a picture of the consumer unit/main fusebox for me?',
        timestamp: mins(15),
        channelType: 'messenger',
        isRead: true,
      },
      {
        id: 'msg-1-3',
        conversationId: 'conv-1',
        direction: 'incoming',
        text: "It's a 4-bed detached, built in 1970. The fuse box is the old ceramic type.",
        timestamp: mins(3),
        channelType: 'messenger',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-2',
    channelType: 'messenger',
    channelId: 'ch-messenger-1',
    contactName: 'Sarah Mitchell',
    contactInitials: 'SM',
    contactAvatarColor: '#FF5722',
    pageName: "Dave's Electrical Services",
    unreadCount: 2,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-2-2',
      conversationId: 'conv-2',
      direction: 'incoming',
      text: 'Great, can you do Tuesday morning? We need the whole consumer unit replaced.',
      timestamp: mins(8),
      channelType: 'messenger',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-2-1',
        conversationId: 'conv-2',
        direction: 'incoming',
        text: 'Hi, are you available this week for an electrical job in Stockport?',
        timestamp: mins(30),
        channelType: 'messenger',
        isRead: true,
      },
      {
        id: 'msg-2-2',
        conversationId: 'conv-2',
        direction: 'incoming',
        text: 'Great, can you do Tuesday morning? We need the whole consumer unit replaced.',
        timestamp: mins(8),
        channelType: 'messenger',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-3',
    channelType: 'messenger',
    channelId: 'ch-messenger-1',
    contactName: 'Tom Hargreaves',
    contactInitials: 'TH',
    contactAvatarColor: '#009688',
    pageName: "Dave's Electrical Services",
    unreadCount: 1,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-3-1',
      conversationId: 'conv-3',
      direction: 'incoming',
      text: 'Do you cover the Stockport area? Need a couple of sockets adding in the kitchen.',
      timestamp: mins(22),
      channelType: 'messenger',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-3-1',
        conversationId: 'conv-3',
        direction: 'incoming',
        text: 'Do you cover the Stockport area? Need a couple of sockets adding in the kitchen.',
        timestamp: mins(22),
        channelType: 'messenger',
        isRead: false,
      },
    ],
  },
  // ── Page Comments ──────────────────────────────────────────────────────────
  {
    id: 'conv-4',
    channelType: 'page_comment',
    channelId: 'ch-page-1',
    contactName: 'Mike Reynolds',
    contactInitials: 'MR',
    contactAvatarColor: '#3F51B5',
    pageName: "Dave's Electrical Services",
    unreadCount: 2,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-4-2',
      conversationId: 'conv-4',
      direction: 'incoming',
      text: 'How much do you charge for a full consumer unit upgrade?',
      timestamp: mins(45),
      channelType: 'page_comment',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-4-1',
        conversationId: 'conv-4',
        direction: 'incoming',
        text: 'Great work on my neighbour\'s house! Highly recommended.',
        timestamp: hours(1),
        channelType: 'page_comment',
        isRead: true,
      },
      {
        id: 'msg-4-2',
        conversationId: 'conv-4',
        direction: 'incoming',
        text: 'How much do you charge for a full consumer unit upgrade?',
        timestamp: mins(45),
        channelType: 'page_comment',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-5',
    channelType: 'page_comment',
    channelId: 'ch-page-1',
    contactName: 'Diane Walsh',
    contactInitials: 'DW',
    contactAvatarColor: '#E91E63',
    pageName: "Dave's Electrical Services",
    unreadCount: 0,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-5-2',
      conversationId: 'conv-5',
      direction: 'outgoing',
      text: 'Thanks Diane! Really appreciate you taking the time to leave a comment.',
      timestamp: hours(3),
      channelType: 'page_comment',
      isRead: true,
    },
    messages: [
      {
        id: 'msg-5-1',
        conversationId: 'conv-5',
        direction: 'incoming',
        text: '5 stars! Dave sorted our outdoor lighting in no time. Will definitely use again.',
        timestamp: hours(4),
        channelType: 'page_comment',
        isRead: true,
      },
      {
        id: 'msg-5-2',
        conversationId: 'conv-5',
        direction: 'outgoing',
        text: 'Thanks Diane! Really appreciate you taking the time to leave a comment.',
        timestamp: hours(3),
        channelType: 'page_comment',
        isRead: true,
      },
    ],
  },
  // ── WhatsApp ───────────────────────────────────────────────────────────────
  {
    id: 'conv-6',
    channelType: 'whatsapp',
    channelId: 'ch-wa-1',
    contactName: 'Liam Fletcher',
    contactInitials: 'LF',
    contactAvatarColor: '#FF9800',
    pageName: "Dave's Electrical Services",
    unreadCount: 2,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-6-2',
      conversationId: 'conv-6',
      direction: 'incoming',
      text: 'Got a sparking socket in the kitchen, is that something you can sort today?',
      timestamp: mins(5),
      channelType: 'whatsapp',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-6-1',
        conversationId: 'conv-6',
        direction: 'incoming',
        text: 'Hi Dave, got your number from a friend. Are you taking on new jobs?',
        timestamp: mins(15),
        channelType: 'whatsapp',
        isRead: true,
      },
      {
        id: 'msg-6-2',
        conversationId: 'conv-6',
        direction: 'incoming',
        text: 'Got a sparking socket in the kitchen, is that something you can sort today?',
        timestamp: mins(5),
        channelType: 'whatsapp',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-7',
    channelType: 'whatsapp',
    channelId: 'ch-wa-1',
    contactName: 'Rachel Okafor',
    contactInitials: 'RO',
    contactAvatarColor: '#00BCD4',
    pageName: "Dave's Electrical Services",
    unreadCount: 0,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-7-3',
      conversationId: 'conv-7',
      direction: 'outgoing',
      text: 'Great, I will be with you at 2pm on Friday. See you then.',
      timestamp: hours(1),
      channelType: 'whatsapp',
      isRead: true,
    },
    messages: [
      {
        id: 'msg-7-1',
        conversationId: 'conv-7',
        direction: 'incoming',
        text: 'Hi, I need an EV charger installed at my house. Can you quote?',
        timestamp: hours(3),
        channelType: 'whatsapp',
        isRead: true,
      },
      {
        id: 'msg-7-2',
        conversationId: 'conv-7',
        direction: 'outgoing',
        text: 'I can come and take a look and give you a free no-obligation quote. What\'s the address and when would suit you?',
        timestamp: hours(2),
        channelType: 'whatsapp',
        isRead: true,
      },
      {
        id: 'msg-7-3',
        conversationId: 'conv-7',
        direction: 'outgoing',
        text: 'Great, I will be with you at 2pm on Friday. See you then.',
        timestamp: hours(1),
        channelType: 'whatsapp',
        isRead: true,
      },
    ],
  },
  {
    id: 'conv-8',
    channelType: 'whatsapp',
    channelId: 'ch-wa-1',
    contactName: 'Gary Nuttall',
    contactInitials: 'GN',
    contactAvatarColor: '#795548',
    pageName: "Dave's Electrical Services",
    unreadCount: 1,
    isAutoReplied: true,
    lastMessage: {
      id: 'msg-8-2',
      conversationId: 'conv-8',
      direction: 'outgoing',
      text: "Thanks for your message! We aim to respond within 2 hours during working hours.",
      timestamp: hours(2),
      channelType: 'whatsapp',
      isRead: true,
    },
    messages: [
      {
        id: 'msg-8-1',
        conversationId: 'conv-8',
        direction: 'incoming',
        text: 'Dave, my outdoor lights have stopped working. Any chance you can take a look?',
        timestamp: hours(2),
        channelType: 'whatsapp',
        isRead: true,
      },
      {
        id: 'msg-8-2',
        conversationId: 'conv-8',
        direction: 'outgoing',
        text: "Thanks for your message! We aim to respond within 2 hours during working hours.",
        timestamp: hours(2),
        channelType: 'whatsapp',
        isRead: true,
      },
    ],
  },
  // ── SMS ────────────────────────────────────────────────────────────────────
  {
    id: 'conv-9',
    channelType: 'sms',
    channelId: 'ch-sms-1',
    contactName: 'Phil Barker',
    contactInitials: 'PB',
    contactAvatarColor: '#607D8B',
    pageName: "Dave's Electrical Services",
    unreadCount: 2,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-9-2',
      conversationId: 'conv-9',
      direction: 'incoming',
      text: 'The trip switch keeps going. Happens every time we turn the oven on.',
      timestamp: mins(10),
      channelType: 'sms',
      isRead: false,
    },
    messages: [
      {
        id: 'msg-9-1',
        conversationId: 'conv-9',
        direction: 'incoming',
        text: 'Hi Dave, got your number from a leaflet. Kitchen sockets keep tripping.',
        timestamp: mins(25),
        channelType: 'sms',
        isRead: true,
      },
      {
        id: 'msg-9-2',
        conversationId: 'conv-9',
        direction: 'incoming',
        text: 'The trip switch keeps going. Happens every time we turn the oven on.',
        timestamp: mins(10),
        channelType: 'sms',
        isRead: false,
      },
    ],
  },
  {
    id: 'conv-10',
    channelType: 'sms',
    channelId: 'ch-sms-1',
    contactName: 'Janet Crossley',
    contactInitials: 'JC',
    contactAvatarColor: '#E91E63',
    pageName: "Dave's Electrical Services",
    unreadCount: 0,
    isAutoReplied: false,
    lastMessage: {
      id: 'msg-10-4',
      conversationId: 'conv-10',
      direction: 'outgoing',
      text: "No problem at all Janet. See you Wednesday at 10.",
      timestamp: hours(2),
      channelType: 'sms',
      isRead: true,
    },
    messages: [
      {
        id: 'msg-10-1',
        conversationId: 'conv-10',
        direction: 'incoming',
        text: 'Dave, my smoke alarm keeps beeping. Is that something you can fix?',
        timestamp: hours(6),
        channelType: 'sms',
        isRead: true,
      },
      {
        id: 'msg-10-2',
        conversationId: 'conv-10',
        direction: 'outgoing',
        text: 'Hi Janet, yes — usually just a battery but worth checking the unit too. I can pop round Wednesday if that suits?',
        timestamp: hours(5),
        channelType: 'sms',
        isRead: true,
      },
      {
        id: 'msg-10-3',
        conversationId: 'conv-10',
        direction: 'incoming',
        text: 'Wednesday morning would be perfect, thank you.',
        timestamp: hours(3),
        channelType: 'sms',
        isRead: true,
      },
      {
        id: 'msg-10-4',
        conversationId: 'conv-10',
        direction: 'outgoing',
        text: "No problem at all Janet. See you Wednesday at 10.",
        timestamp: hours(2),
        channelType: 'sms',
        isRead: true,
      },
    ],
  },
];

export const DEFAULT_CREDENTIALS: ChannelCredentials = {
  facebook: { appId: '', appSecret: '', pageAccessToken: '', pageId: '' },
  whatsapp: { phoneNumberId: '', accessToken: '', webhookVerifyToken: '', businessAccountId: '' },
  twilio: { accountSid: '', authToken: '', phoneNumber: '' },
};

export const DEFAULT_SETTINGS: AppSettings = {
  businessName: "Dave's Electrical Services",
  tradeType: 'electrician',
  autoReply: {
    enabled: false,
    message: "Thanks for your message! We aim to respond within 2 hours during working hours. For emergencies, please call us directly.",
    outsideHoursOnly: true,
    workingHoursStart: '08:00',
    workingHoursEnd: '18:00',
  },
  quickReplies: [
    {
      id: 'qr-1',
      label: 'Request CU photo',
      category: 'Qualifying',
      text: "Thank you for your enquiry, I appreciate it.  Please could you take a picture of the consumer unit/main fusebox for me?",
    },
    {
      id: 'qr-2',
      label: 'Yes, I cover that area',
      category: 'Qualifying',
      text: "Hi! Yes, I cover that area — no problem at all. Can you tell me a bit more about what needs doing? Happy to come and have a look and give you a free quote.",
    },
    {
      id: 'qr-3',
      label: 'Free quote offer',
      category: 'Booking',
      text: "I can come and take a look and give you a free no-obligation quote. What's the address and when would suit you?",
    },
    {
      id: 'qr-4',
      label: 'What days work?',
      category: 'Booking',
      text: "That sounds like something I can definitely help with. What days work best for you? I can usually get round within a day or two.",
    },
    {
      id: 'qr-5',
      label: 'Slow reply apology',
      category: 'Holding',
      text: "Sorry for the slow reply — been on a job all day. I'll give you a ring this evening if that's okay, or feel free to call me on the number on my page.",
    },
    {
      id: 'qr-6',
      label: 'Thank you for review',
      category: 'Follow-up',
      text: "Thanks for the kind words, really appreciate it! If you ever need anything else doing, just give me a shout.",
    },
  ],
  credentials: DEFAULT_CREDENTIALS,
};
